//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class student_tablemvcEntities1 : DbContext
    {
        public student_tablemvcEntities1()
            : base("name=student_tablemvcEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<state_db> state_db { get; set; }
        public virtual DbSet<student> students { get; set; }
    
        public virtual ObjectResult<sp_district_Result> sp_district(Nullable<int> sid)
        {
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_district_Result>("sp_district", sidParameter);
        }
    
        public virtual int sp_insert_student(Nullable<int> sid, Nullable<int> did, string name, Nullable<int> age, string ph)
        {
            var sidParameter = sid.HasValue ?
                new ObjectParameter("sid", sid) :
                new ObjectParameter("sid", typeof(int));
    
            var didParameter = did.HasValue ?
                new ObjectParameter("did", did) :
                new ObjectParameter("did", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var phParameter = ph != null ?
                new ObjectParameter("ph", ph) :
                new ObjectParameter("ph", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_student", sidParameter, didParameter, nameParameter, ageParameter, phParameter);
        }
    
        public virtual ObjectResult<sp_states_Result> sp_states()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_states_Result>("sp_states");
        }
    }
}
